development:
  adapter: postgresql
  encoding: unicode
  database: stokboard_development
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: stokboard_production
  pool: 5
  username: postgres
  password:
